spring.application.name=auth-service
spring.config.import=optional:configserver:http://localhost:8888
server.port=8081

# Database specific to this service
spring.datasource.url=jdbc:postgresql://localhost:5432/skillsync_auth
spring.jpa.properties.hibernate.default_schema=auth

# Auth specific settings
jwt.access-expiration=900000
jwt.refresh-expiration=604800000

# ========== Gmail SMTP Configuration (JavaMailSender) ==========
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aksahoo1097@gmail.com
spring.mail.password=${GMAIL_APP_PASSWORD:sosl hqxq fibe bpyp}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

