spring.application.name=auth-service
spring.config.import=optional:configserver:http://localhost:8888
server.port=8081

# Database specific to this service
spring.datasource.url=jdbc:postgresql://localhost:5432/skillsync_auth
spring.jpa.properties.hibernate.default_schema=auth

# Auth specific settings
jwt.access-expiration=900000
jwt.refresh-expiration=604800000
