spring.application.name=mentor-service
spring.config.import=optional:configserver:http://localhost:8888
server.port=8083

# Database specific to this service
spring.datasource.url=jdbc:postgresql://localhost:5432/skillsync_mentor
spring.jpa.properties.hibernate.default_schema=mentors

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
