server.port=8083

spring.application.name=mentor-service

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/skillsync_mentor
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=mentors
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# Actuator
management.endpoints.web.exposure.include=health,info

logging.level.com.skillsync=DEBUG
