spring.application.name=group-service
spring.config.import=optional:configserver:http://localhost:8888
server.port=8086

# Database specific to this service
spring.datasource.url=jdbc:postgresql://localhost:5432/skillsync_group
spring.jpa.properties.hibernate.default_schema=groups
